apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swagger-ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000,https://localhost:3000,http://172.16.212.76:3000,http://front.oguogu.store:3000,http://front.172.16.212.76.end:3000"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT,GET,POST,DELETE,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/cors-expose-headers: "*"
spec:
  rules:
    - host: "www.bbang.site"
      http:
        paths:
          - path: /member-api
            pathType: Prefix
            backend:
              service:
                name: member
                port:
                  number: 80
          - path: /channel-api
            pathType: Prefix
            backend:
              service:
                name: channel
                port:
                  number: 80
          - path: /schedule-api
            pathType: Prefix
            backend:
              service:
                name: schedule
                port:
                  number: 80
          - path: /board-api
            pathType: Prefix
            backend:
              service:
                name: board
                port:
                  number: 80
          - path: /reply-api
            pathType: Prefix
            backend:
              service:
                name: reply
                port:
                  number: 80
          - path: /memo-api
            pathType: Prefix
            backend:
              service:
                name: memo
                port:
                  number: 80
          - path: /when-to-meet-api
            pathType: Prefix
            backend:
              service:
                name: whentomeet
                port:
                  number: 80
          - path: /v3/swagger-ui.html
            pathType: Prefix
            backend:
              service:
                name: swagger-ui
                port:
                  number: 80
