apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-deployment
  namespace: meeton-backend
  labels:
    app: meeton-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: board
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
        - name: board-container
          image: your-ecr-repo-url/your-image:tag
          ports:
            - containerPort: 80
