apiVersion: apps/v1
kind: Deployment
metadata:
  name: channel-deployment
  namespace: meeton-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: channel
  template:
    metadata:
      labels:
        app: channel
    spec:
      containers:
        - name: channel-container
          image: your-ecr-repo-url/your-image:tag
          ports:
            - containerPort: 80
