apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-deployment
  namespace: meeton-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
        - name: member-container
          image: your-ecr-repo-url/member-image:tag
          ports:
            - containerPort: 80
