apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: meeton-backend
  labels: meeton-backend
spec:
  selector:
    app: member
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
