apiVersion: v1
kind: Service
metadata:
  name: channel-service
  namespace: meeton-backend
  labels: meeton-backend
spec:
  selector:
    app: channel
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
