apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: meeton-backend
  labels:
    app: meeton-backend
spec:
  selector:
    matchLabels:
      app: meeton-backend
  serviceName: kafka
  replicas: 3 # Use 3 replicas for production Kafka
  template:
    metadata:
      labels:
        app: meeton-backend
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          ports:
            - containerPort: 9092
              name: kafka
          envFrom:
            - configMapRef:
                name: kafka-config
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.pod.name # Dynamic broker ID
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://${KAFKA_ADVERTISED_HOST}:${KAFKA_ADVERTISED_PORT}
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://${KAFKA_LISTENERS_HOST}:${KAFKA_LISTENERS_PORT}
          volumeMounts:
            - name: datadir
              mountPath: /kafka
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp2
        resources:
          requests:
            storage: 10Gi
