apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: meeton-backend
  labels:
    app: meeton-backend
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app: meeton-backend
