apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: meeton-backend
  labels:
    app: meeton-backend
spec:
  selector:
    matchLabels:
      app: meeton-backend
  serviceName: zookeeper
  replicas: 3
  template:
    metadata:
      labels:
        app: meeton-backend
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper:latest
          ports:
            - containerPort: 2181
              name: client
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_SERVER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.pod.name
          volumeMounts:
            - name: datadir
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp2
        resources:
          requests:
            storage: 10Gi
