apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: meeton-backend
  labels:
    app: meeton-backend
data:
  KAFKA_ADVERTISED_HOST: kafka-0.kafka.meeton-backend.svc.cluster.local
  KAFKA_ADVERTISED_PORT: "9092"
  KAFKA_LISTENERS_HOST: "0.0.0.0"
  KAFKA_LISTENERS_PORT: "9092"
  KAFKA_ZOOKEEPER_CONNECT: zookeeper-0.zookeeper.meeton-backend.svc.cluster.local:2181,zookeeper-1.zookeeper.meeton-backend.svc.cluster.local:2181,zookeeper-2.zookeeper.meeton-backend.svc.cluster.local:2181
