apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: meeton-backend
  labels:
    app: meeton-backend
data:
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0.kafka.meeton-backend.svc.cluster.local:9092
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
